name: C Compiler

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install gcc
        run: 
          apt install gcc
          
      - name: Run Compiler
        run: 
          gcc 1.c -o one -lpthread
          
      - name: Set Execute Permissions
        run: chmod +x *
